// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeuQbjLWGyxLDVLVNIC9SUMe-upeRN2zI',
    appId: '1:1085731614579:web:7931f1b076b9efe364df06',
    messagingSenderId: '1085731614579',
    projectId: 'hello-altr',
    authDomain: 'hello-altr.firebaseapp.com',
    storageBucket: 'hello-altr.firebasestorage.app',
    measurementId: 'G-7KTTZVBV0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx9JCaV3W7okxokjZ7I5P1bIZHtXw6op8',
    appId: '1:1085731614579:android:0eb3f347c10a7c9b64df06',
    messagingSenderId: '1085731614579',
    projectId: 'hello-altr',
    storageBucket: 'hello-altr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFx4qPGmR37GJLygt0xMwnshnFHxbQ4P4',
    appId: '1:1085731614579:ios:81f4d6e9aeaaa3c764df06',
    messagingSenderId: '1085731614579',
    projectId: 'hello-altr',
    storageBucket: 'hello-altr.firebasestorage.app',
    iosClientId: '1085731614579-7o5itj8fbh0h7prujtt4suvqsl6latg4.apps.googleusercontent.com',
    iosBundleId: 'hello.altr.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFx4qPGmR37GJLygt0xMwnshnFHxbQ4P4',
    appId: '1:1085731614579:ios:81f4d6e9aeaaa3c764df06',
    messagingSenderId: '1085731614579',
    projectId: 'hello-altr',
    storageBucket: 'hello-altr.firebasestorage.app',
    iosClientId: '1085731614579-7o5itj8fbh0h7prujtt4suvqsl6latg4.apps.googleusercontent.com',
    iosBundleId: 'hello.altr.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeuQbjLWGyxLDVLVNIC9SUMe-upeRN2zI',
    appId: '1:1085731614579:web:a8da1ede5f3453d964df06',
    messagingSenderId: '1085731614579',
    projectId: 'hello-altr',
    authDomain: 'hello-altr.firebaseapp.com',
    storageBucket: 'hello-altr.firebasestorage.app',
    measurementId: 'G-1HF1TW3DSD',
  );
}
